### ISSUE TITLE
Streaming access by external browser

### ISSUE THREAD

**Issue by gabeale** [Esser50K/PiCameleon#15]
Dear friend,

I have properly installed the docker on PiZero and tested it. However I'm not able to access the _mjpg_ or _h264_ Picamera streaming output. I'm wondering if it is because I need to map container ports to the external world (and which ones?)

What is the right procedure to access the server by a browser in order to see the camera streaming in _mjpg_ or _rtsp_ by external application like VLC or equivalent?

Thx

**Comment by Esser50K** [comment]
Great that you're experimenting with the project!

Yes to access the streams you need to expose some ports of the container. You can check the config that you are using to know which ones.

For example if you're using [this](https://github.com/Esser50K/PiCameleon/blob/main/picameleon/configs/stream_server_config.json) config you need to expose port 5566

However you cannot access the stream directly from a browser or VLC as that is not part of the scope of this project, this project is just to have an interface for the camera to access it by multiple processes and remotely.

If you want to view a stream in your browser you need to implement a MJPG server that fetches the frames from PiCameleon.
MJPG Server example from the original picamera library: https://picamera.readthedocs.io/en/release-1.13/recipes2.html#web-streaming

But instead of picamera you can use the [client](https://github.com/Esser50K/PiCameleon/blob/main/picameleon/client/client.py) of PiCameleon to fetch the frames.
Here is an example of how to fetch jpg frames: https://github.com/Esser50K/PiCameleon/blob/main/examples/fetch_and_display_jpg.py

Hope this helps!

**Comment by gabeale** [comment]
Thanks André for the given details. I still need some help to get it working.
I understood that I need to run picameleon docker exposing some ports according to the configuration used. Question is: how to select the desired configuration?
I also understood that a python script is required to fetch the streaming. Question is: shall I run this script inside the docker container or outside it? In the first case I tried but found that some modules are missing (see excerpt below).
Am I on the right way?
Thx!
![Schermata del 2021-08-06 15-24-37](https://user-images.githubusercontent.com/41168339/128517071-83450567-bde6-42ac-86f5-9afd67fddf7e.png)

**Comment by Esser50K** [comment]
the client doesn't need to be run inside a container (nor does PiCameleon, it's just easier).
You just need to install the necessary packages
```
pip3 install opencv-python
```

Yeah I think you are on the right path. Just read those examples so you know how to retrieve individual frames in different formats and then you can plug it in the webserver thing to send an mjpg stream

**Comment by gabeale** [comment]
Dear Esser, thx for your feedback.
Unfortunately I'm still struggling to concatenate the two examples you have given (i e. picamera web streaming and picameleon  JPEG fetch and display).
Basically I'm in trouble in sending the mjpeg to web server that is expecting an object (i e. "StreamingOutput" in the script) whereas picameleon is using the class labelled "OpenCVDecoder").
Can you please help me a little more?
Thank you for your patience
Cheers

**Comment by Esser50K** [comment]
I'll try to find time to write another example that does this :)

By the way, the classes are just there to be like "writable" objects, the important thing is that they implement the `write` method. That method receives the frames and can do whatever it wants with it. In your case it would be writing the image to the HTTP connection.

I'll reopen this so I don't forget

**Comment by gabeale** [comment]
Great!
Thank you so much! :)

**Comment by gabeale** [comment]
Dear Esser,
Have you had the chance to look after the code for web streaming using Picameleon?
Keep in touch
Thx

**Comment by Esser50K** [comment]
Hey there, sorry for the delay, been a bit busy. The example was committed here 30cf7bf60accd776f6876e8ee92f315937499dca.

If you look at the example and the one given from `picamera` you'll see they are basically the same and that `picameleon` attempts to have a similar feeling as if the camera was local.

**Comment by gabeale** [comment]
Dear Esser,
thank you very much for the example you have provided (_30cf7bf_). I'm very happy to say that I got it working inside a container!
Now I'm trying to add the video recording feature using the "trigger_video_capture.py" example.
At the moment I'm not understanding a couple of things as follows:
1. _json_config_ file is not available in the container: shall I add it?
2. If so, can I take the example configuration?
3. "stream_id" in python is set to "stream1" but i don't see if it is recalled somewhere else in the code.
4. shall I add one instance to picameleon or it is sufficient to concatenate the web_streaming.py with trigger_video_capture.py codes?
Keep in touch, thx

**Comment by Esser50K** [comment]
Glad it is working for you :D I also managed to get it working in a couple of different ways with the h264 format, but that requires a more complex setup. It's a bit hard to write an example with just that.

Please post your questions in a new issue and give it the `question` tag. Thanks
